name = "enough-home"
main = "src/index.js"
compatibility_date = "2023-07-10"

[site]
bucket = "./assets"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# Service binding for outbound emails
[[services]]
binding = "OUTBOUND_EMAILS"
service = "enough-outbound-emails"

[vars]
COMING_SOON = "TRUE"  # Set to "TRUE" to enable coming soon mode
