name = "enough-home"
main = "src/index.js"
compatibility_date = "2023-07-10"

[site]
bucket = "./assets"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# Service bindings
[[services]]
binding = "OUTBOUND_EMAILS"
service = "enough-outbound-emails"

[[services]]
binding = "INBOX_UI"
service = "enough-inbox-ui"

# Environment variables
[vars]
INBOX_UI_URL = "https://enough-inbox-ui.workers.dev"
COMING_SOON = "TRUE"  # Set to "TRUE" to enable coming soon mode
