name = "enough-home"
main = "src/index.js"
compatibility_date = "2023-07-10"

[site]
bucket = "./assets"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[vars]
COMING_SOON = "TRUE"  # Set to "TRUE" to enable coming soon mode

